### PR TITLE
Add unit test suite

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR introduces BDD testing and unit testing using Codeception + phpunit.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Should be fine to use now and extend.

**Comment by Maikuolan** [comment]
Looks good so far, and thanks for setting this up for us. :-)

I'm not sure that we need to specifically include `config.ini` in the PRs though, because that should already be being taken of by `cp $TRAVIS_BUILD_DIR/vault/config.ini.RenameMe $TRAVIS_BUILD_DIR/vault/config.ini` in `.travis.yml`.

---

*Replying here, but referencing #130, due to this reply being applicable to both PRs.*

**Comment by DanielRuf** [comment]
It was probably by accident. I would either move it to the test support folder (don't be Travis CI specific) or try to implement the copy part in the testsuite or in .travis.yml.

**Comment by DanielRuf** [comment]
Probably `_support` is best so we can test dufferent configs from there without creating the file in the application and I might have to ignore the output and data folders.

**Comment by DanielRuf** [comment]
Probably `_support` is best so we can test different configs from there without creating the file in the application and I might have to ignore the output and data folders.

**Comment by Maikuolan** [comment]
Sounds good. :-)

Being able to test multiple different configurations could definitely be useful too, in order to be able to test any concerns that might potentially behave differently per different configuration.

**Comment by DanielRuf** [comment]
I will adjust the .gitignore file to also ignore the config files.

Are there more files which should not be committed like logfiles?

**Comment by Maikuolan** [comment]
> Are there more files which should not be committed like logfiles?

We probably won't need to worry too much about that. The configuration directives that control the filenames used for logfiles are empty by default, so, users will need to specify the filenames for these in their configuration if they want CIDRAM to log anything, so, the chance of accidentally committing logfiles isn't super high, I think.

**Comment by DanielRuf** [comment]
Sure but don't forget those who clone the project, use it and track the needed changes using Git and version them ;-)

**Comment by Maikuolan** [comment]
(I don't think there's anything else though).

**Comment by Maikuolan** [comment]
> Sure but don't forget those who clone the project, use it and track the needed changes using Git and version them ;-)

Good point. '^.^

**Comment by Maikuolan** [comment]
Actually, `cache.dat` should probably be ignored, too. `cache.dat` doesn't exist in the remote, but is created automatically when CIDRAM executes (contains cache data), so, is something that could potentially be accidentally committed. Maybe `frontend.dat` (under `vault/fe_assets`), too. `frontend.dat` also doesn't exist in the remote, but is created automatically when accessing the CIDRAM front-end (if the front-end has been enabled, at least), and can contain login hashes and such, which should never be committed. I'll mention here if I think of anything else.

**Review by DanielRuf — COMMENTED** [review]
Same here. Ternary operator is not great for long lines.

**Comment by DanielRuf** [comment]
It seems CI fails now. Can you check that @Maikuolan?

**Comment by Maikuolan** [comment]
> It seems CI fails now. Can you check that @Maikuolan?

Yep. I'll check that in the morning. :-)

**Comment by Maikuolan** [comment]
> > It seems CI fails now. Can you check that @Maikuolan?
>
> Yep. I'll check that in the morning. :-)

Following up on that: The cause of the failure, I think, is the deprecation warning generated for `Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()`, consequently causing the assertion for `LoaderCest:testNoErrors` to fail.

The pull request at https://github.com/Codeception/Codeception/pull/5555 should resolve the problem, I think. Changing the `2.3` in:

```YAML
    "require-dev": {
        "codeception/codeception": "^2.3"
    }
```

..to whichever newer version number we need in order to benefit from that PR, should theoretically fix our current test failures, I think. Except that, there hasn't been a new tagged release for Codeception yet since that PR was merged. Looking at the dates for previous tagged releases for Codeception, it seems that they're releasing new versions roughly once per month on average, and the current latest version was released exactly one month ago now to-date, so.. I would cautiously assume that there'll be a new tagged release at some point during the coming week or thereabouts. As long as this assumption pans out.. if we kept our PRs here open until the next tagged release, and then bumped our required Codeception versions accordingly.. the failures will most likely disappear, I think.

It seems though, that the aforementioned Codeception PR targets their 3x branch, and we're currently requiring a 2x version, so.. I'm not sure whether switching to a 3x version could create more work elsewhere, or possible compatibility problems (they've mentioned in some of their issues before about dropping support for older PHP versions; shouldn't be a problem for CIDRAM >= 2.0.0, due to CIDRAM >= 2.0.0 requiring PHP => 7.2 anyway, but could possibly be a problem for CIDRAM < 2.0.0, due to the PHP => 5.4 requirement).

**Comment by Maikuolan** [comment]
Some related comments (the linked, plus a few of the immediately subsequent comments): https://github.com/Codeception/Codeception/issues/5532#issuecomment-503202387

**Comment by DanielRuf** [comment]
Checking if we can pin the deps or just have to wait. Does not seem to happen on the other PR.

**Comment by DanielRuf** [comment]
Dependencies are the same.

**Comment by DanielRuf** [comment]
> Some related comments (the linked, plus a few of the immediately subsequent comments): [Codeception/Codeception#5532 (comment)](https://github.com/Codeception/Codeception/issues/5532#issuecomment-503202387)

Not relevant for us. I have rebased on `v1` to get the `Trusty` build setup.

**Comment by DanielRuf** [comment]
> ..to whichever newer version number we need in order to benefit from that PR

If there is no lockfile composer will pull the latest release which satisfies this Semver selector. Both builds use the same dependencies: https://www.diffchecker.com/ktGF0NF1

**Comment by Maikuolan** [comment]
> Not relevant for us. I have rebased on `v1` to get the `Trusty` build setup.

Sounds good :+1:

**Comment by DanielRuf** [comment]
Hm, weird. We use no caches and no lockfiles. At first I thought it is a difference between the branches. I'll try to add a lockfile which should resolve this. Probably a deep peer dependency by Symfony.

**Comment by DanielRuf** [comment]
Hm, weird. We use no caches and no lockfiles. Also an old lockfile has this issue now.

**Comment by DanielRuf** [comment]
Last green CI build: https://travis-ci.org/CIDRAM/CIDRAM/builds/534753199
Last broken CI build: https://travis-ci.org/CIDRAM/CIDRAM/builds/547648765

**Comment by Maikuolan** [comment]
Cool.. Seems to be working since your latest fix. :-)

With the reversion: Anything in my commit there that might've broke something? I can easily re-commit, but I don't want to break it again, if I can avoid that, if there was something there that I might've done accidentally. '^.^

(And I'll sort out that ternary too, of course).

**Comment by DanielRuf** [comment]
I'll remove the reverted commit. Should not be related. The files were generated by Codeception and follow specific PSR patterns.

**Review by Maikuolan — APPROVED** [review]

**Comment by Maikuolan** [comment]
Replaced the ternary with standard if{}/else{} and slightly changed some comments to try to help a little. Tests seem to all be passing successfully now, and seems good AFAICT. :-)

**Pull request merged**
