### PR TITLE
Add unit test suite

### PR DESCRIPTION
**Pull request by DanielRuf**
(cherry picked from commit 4ed45e4620ac3e8c569dde565435fa9eeb18f6ff)

### CODE REVIEW

**Comment by DanielRuf** [comment]
Mh https://travis-ci.org/CIDRAM/CIDRAM/jobs/547203713#L403

**Comment by DanielRuf** [comment]
@Maikuolan I have added a bit of code because so far we can not pass a custom configuration as the paths are hardcoded (`__DIR__ . '/vault'`, `vault/config.ini` and so on).

**Comment by DanielRuf** [comment]
Also what about composer.lock? It would be needed for pinning the codeception version and its dependencies for contributors

**Comment by Maikuolan** [comment]
`<div id="detected">Your access to this page was denied because you attempted to access this page using an invalid IP address.</div>`

Technically correct, seeing as the tests aren't being executed via a typical webserver, and the tests aren't faking any particular real IP address. :P

Anyway, if tests pass, and we're seeing what we're supposed to see.. cool cool. ^.^

> Also what about composer.lock? It would be needed for pinning the codeception version and its dependencies for contributors

True, and good point; I hadn't thought about that before. We should definitely account for that.

> @Maikuolan I have added a bit of code because so far we can not pass a custom configuration as the paths are hardcoded (`__DIR__ . '/vault'`, `vault/config.ini` and so on).

Sounds good. :+1:

I should mention, too (so that the knowledge about this can be out there): When we update "core" files (e.g., `config.php`, `functions.php`, etc; "core", in this context, referring to any of the core CIDRAM files that we intend the front-end updates page to be able to fetch/update), we'll also need to update the corresponding checksums/hashes for the updated files in the component metadata (in `components.dat`), in order for the front-end updates page to not reject those files when users update via the front-end. This is easy to do though, and should be one of the last things done for PRs and such wherever these files are changed (in case the same files are changed again prior to merging; to avoid needing to update these checksums/hashes multiple times per PR), so, I can sort that out when we're ready to merge anyway.

**Comment by DanielRuf** [comment]
Right, you can push to the same branch / PR any time. I might add some more comments for the tests later today or tomorrow to describe why the code in the tests is like this.

For E2E / acceptance I will test if we can use the native testserver of PHP.

**Comment by Maikuolan** [comment]
Strange that the later PHP versions were passing for v2, but not for v1. I'm not really sure why one was passing while the other was failing. It seems like the fix used for v1 (`"symfony/event-dispatcher": "3.4.28"` in `composer.json`), maybe isn't needed for v2, but should we maybe add it anyway, for consistency, and in case it suddenly stops working for v2 in the future?

**Comment by DanielRuf** [comment]
I'll check that.

**Review by Maikuolan — APPROVED** [review]

**Comment by Maikuolan** [comment]
Replaced the ternary with standard if{}/else{} and slightly changed some comments to try to help a little. Tests seem to all be passing successfully now, and seems good AFAICT. :-)

**Pull request merged**
